/* Test BOLT PR #1228 zero-fee commitment test vectors */
#include "config.h"
#include <stdio.h>
#include <stdbool.h>
#include <inttypes.h>
#include <ccan/array_size/array_size.h>
#include <ccan/err/err.h>
#include <ccan/str/hex/hex.h>
#include <ccan/tal/grab_file/grab_file.h>

/* Need this for deterministic signatures to match test vectors */
static bool print_superverbose;
#define SUPERVERBOSE(...)                                       \
        do { if (print_superverbose) printf(__VA_ARGS__); } while(0)
#define PRINT_ACTUAL_FEE

#include "../commit_tx.c"
#include <bitcoin/preimage.h>
#include <bitcoin/privkey.h>
#include <common/channel_id.h>
#include <common/daemon.h>
#include <common/json_parse_simple.h>
#include <common/key_derive.h>
#include <common/memleak.h>
#include <common/setup.h>
#include <common/status.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

/* JSON parsing requires jsmn */
#include <external/jsmn/jsmn.h>

static struct bitcoin_txid txid_from_hex(const char *hex)
{
	struct bitcoin_txid txid;
	if (!bitcoin_txid_from_hex(hex, strlen(hex), &txid))
		abort();
	return txid;
}

static struct secret secret_from_hex(const char *hex)
{
	struct secret s;
	size_t len = strlen(hex);
	if (!hex_decode(hex, len, &s, sizeof(s)))
		abort();
	return s;
}

static struct pubkey pubkey_from_hex(const char *hex)
{
	struct pubkey p;
	if (!pubkey_from_hexstr(hex, strlen(hex), &p))
		abort();
	return p;
}

static void sha256_from_hex(const char *hex, struct sha256 *hash)
{
	if (!hex_decode(hex, strlen(hex), hash, sizeof(*hash)))
		abort();
}


int main(int argc, char *argv[])
{
	const tal_t *ctx = tal(NULL, char);
	jsmn_parser parser;
	jsmntok_t *toks;
	int tok_count;
	char *json;
	const char *json_file;

	common_setup(argv[0]);
	chainparams = chainparams_for_network("bitcoin");

	/* Deterministic signatures for test vector matching */
	dev_no_signature_grind = true;

	/* Find test vectors file */
	if (argc > 1) {
		json_file = argv[1];
	} else {
		/* Try default locations */
		json_file = "tests/zero-fee-commitments-test.json";
		json = grab_file_str(ctx, json_file);
		if (!json) {
			printf("Test vectors file not found, skipping\n");
			printf("PASS (no test vectors)\n");
			goto cleanup;
		}
	}

	json = grab_file_str(ctx, json_file);
	if (!json) {
		errx(1, "Could not load test vectors from %s", json_file);
	}

	printf("# ============================================================\n");
	printf("# BOLT PR #1228 Zero-Fee Commitment Test Vector Validation\n");
	printf("# Test vectors from: %s\n", json_file);
	printf("# ============================================================\n\n");

	/* Parse JSON */
	jsmn_init(&parser);
	toks = tal_arr(ctx, jsmntok_t, 10000);
	tok_count = jsmn_parse(&parser, json, strlen(json), toks, tal_count(toks));
	if (tok_count < 0) {
		errx(1, "Failed to parse JSON test vectors");
	}

	/* Extract global parameters */
	const jsmntok_t *local_funding_priv_tok = json_get_member(json, toks, "local_funding_priv");
	const jsmntok_t *remote_funding_priv_tok = json_get_member(json, toks, "remote_funding_priv");
	const jsmntok_t *funding_txid_tok = json_get_member(json, toks, "funding_txid");
	const jsmntok_t *funding_index_tok = json_get_member(json, toks, "funding_index");
	const jsmntok_t *funding_amount_tok = json_get_member(json, toks, "funding_amount_satoshis");
	const jsmntok_t *commitment_number_tok = json_get_member(json, toks, "commitment_number");
	const jsmntok_t *to_self_delay_tok = json_get_member(json, toks, "to_self_delay");
	const jsmntok_t *local_payment_basepoint_secret_tok = json_get_member(json, toks, "local_payment_basepoint_secret");
	const jsmntok_t *local_delayed_payment_basepoint_secret_tok = json_get_member(json, toks, "local_delayed_payment_basepoint_secret");
	const jsmntok_t *local_htlc_basepoint_secret_tok = json_get_member(json, toks, "local_htlc_basepoint_secret");
	const jsmntok_t *per_commitment_point_tok = json_get_member(json, toks, "per_commitment_point");
	const jsmntok_t *remote_payment_basepoint_secret_tok = json_get_member(json, toks, "remote_payment_basepoint_secret");
	const jsmntok_t *remote_htlc_basepoint_secret_tok = json_get_member(json, toks, "remote_htlc_basepoint_secret");
	const jsmntok_t *revocation_basepoint_tok = json_get_member(json, toks, "revocation_basepoint");
	const jsmntok_t *tests_tok = json_get_member(json, toks, "tests");

	if (!local_funding_priv_tok || !remote_funding_priv_tok || !funding_txid_tok ||
	    !funding_amount_tok || !tests_tok) {
		errx(1, "Missing required fields in test vectors JSON");
	}

	/* Parse global parameters */
	char *local_funding_priv_hex = json_strdup(ctx, json, local_funding_priv_tok);
	char *remote_funding_priv_hex = json_strdup(ctx, json, remote_funding_priv_tok);
	char *funding_txid_hex = json_strdup(ctx, json, funding_txid_tok);
	char *per_commitment_point_hex = json_strdup(ctx, json, per_commitment_point_tok);
	char *revocation_basepoint_hex = json_strdup(ctx, json, revocation_basepoint_tok);
	char *local_payment_basepoint_secret_hex = json_strdup(ctx, json, local_payment_basepoint_secret_tok);
	char *local_delayed_payment_basepoint_secret_hex = json_strdup(ctx, json, local_delayed_payment_basepoint_secret_tok);
	char *local_htlc_basepoint_secret_hex = json_strdup(ctx, json, local_htlc_basepoint_secret_tok);
	char *remote_payment_basepoint_secret_hex = json_strdup(ctx, json, remote_payment_basepoint_secret_tok);
	char *remote_htlc_basepoint_secret_hex = json_strdup(ctx, json, remote_htlc_basepoint_secret_tok);

	struct privkey local_funding_privkey, remote_funding_privkey;
	local_funding_privkey.secret = secret_from_hex(local_funding_priv_hex);
	remote_funding_privkey.secret = secret_from_hex(remote_funding_priv_hex);

	struct pubkey local_funding_pubkey, remote_funding_pubkey;
	if (!pubkey_from_privkey(&local_funding_privkey, &local_funding_pubkey))
		abort();
	if (!pubkey_from_privkey(&remote_funding_privkey, &remote_funding_pubkey))
		abort();

	printf("Local funding pubkey: %s\n", fmt_pubkey(ctx, &local_funding_pubkey));
	printf("Remote funding pubkey: %s\n", fmt_pubkey(ctx, &remote_funding_pubkey));

	struct bitcoin_outpoint funding;
	funding.txid = txid_from_hex(funding_txid_hex);
	u64 funding_index_val;
	if (!json_to_u64(json, funding_index_tok, &funding_index_val))
		errx(1, "Invalid funding_index");
	funding.n = funding_index_val;

	u64 funding_amount_val;
	if (!json_to_u64(json, funding_amount_tok, &funding_amount_val))
		errx(1, "Invalid funding_amount");
	/* Use amount_sat() function for runtime values, not AMOUNT_SAT() macro (which is for constants) */
	struct amount_sat funding_amount = amount_sat(funding_amount_val);

	u64 commitment_number;
	if (!json_to_u64(json, commitment_number_tok, &commitment_number))
		errx(1, "Invalid commitment_number");

	u64 to_self_delay_val;
	if (!json_to_u64(json, to_self_delay_tok, &to_self_delay_val))
		errx(1, "Invalid to_self_delay");
	u16 to_self_delay = to_self_delay_val;

	printf("Funding: %s:%u, amount: %"PRIu64" sats\n",
	       fmt_bitcoin_txid(ctx, &funding.txid), funding.n, funding_amount.satoshis);
	printf("Commitment number: %"PRIu64", to_self_delay: %u\n\n",
	       commitment_number, to_self_delay);

	/* Derive keys from secrets */
	struct secret local_payment_basepoint_secret = secret_from_hex(local_payment_basepoint_secret_hex);
	struct secret local_delayed_payment_basepoint_secret = secret_from_hex(local_delayed_payment_basepoint_secret_hex);
	struct secret local_htlc_basepoint_secret = secret_from_hex(local_htlc_basepoint_secret_hex);
	struct secret remote_payment_basepoint_secret = secret_from_hex(remote_payment_basepoint_secret_hex);
	struct secret remote_htlc_basepoint_secret = secret_from_hex(remote_htlc_basepoint_secret_hex);

	struct pubkey local_payment_basepoint, local_delayed_payment_basepoint, local_htlc_basepoint;
	struct pubkey remote_payment_basepoint, remote_htlc_basepoint;
	struct pubkey per_commitment_point;
	struct pubkey revocation_basepoint;

	if (!pubkey_from_secret(&local_payment_basepoint_secret, &local_payment_basepoint))
		abort();
	if (!pubkey_from_secret(&local_delayed_payment_basepoint_secret, &local_delayed_payment_basepoint))
		abort();
	if (!pubkey_from_secret(&local_htlc_basepoint_secret, &local_htlc_basepoint))
		abort();
	if (!pubkey_from_secret(&remote_payment_basepoint_secret, &remote_payment_basepoint))
		abort();
	if (!pubkey_from_secret(&remote_htlc_basepoint_secret, &remote_htlc_basepoint))
		abort();

	per_commitment_point = pubkey_from_hex(per_commitment_point_hex);
	revocation_basepoint = pubkey_from_hex(revocation_basepoint_hex);

	printf("Basepoints (derived from secrets):\n");
	printf("  local_htlc_basepoint: %s\n", fmt_pubkey(ctx, &local_htlc_basepoint));
	printf("  remote_htlc_basepoint: %s\n", fmt_pubkey(ctx, &remote_htlc_basepoint));
	printf("  per_commitment_point: %s\n\n", fmt_pubkey(ctx, &per_commitment_point));

	/* Derive keys for commitment transaction */
	struct pubkey localkey, remotekey, local_htlckey, remote_htlckey;
	struct pubkey local_delayedkey, revocation_key;

	if (!derive_simple_key(&local_payment_basepoint, &per_commitment_point, &localkey))
		abort();
	/* For option_static_remotekey (required by anchors/zero-fee), remotepubkey
	 * is the payment_basepoint directly, NOT derived with per_commitment_point.
	 * See BOLT 3: "If option_static_remotekey or option_anchors applies to the
	 * commitment transaction, the remotepubkey is simply the remote node's
	 * payment_basepoint" */
	remotekey = remote_payment_basepoint;
	if (!derive_simple_key(&local_htlc_basepoint, &per_commitment_point, &local_htlckey))
		abort();
	if (!derive_simple_key(&remote_htlc_basepoint, &per_commitment_point, &remote_htlckey))
		abort();
	if (!derive_simple_key(&local_delayed_payment_basepoint, &per_commitment_point, &local_delayedkey))
		abort();
	if (!derive_revocation_key(&revocation_basepoint, &per_commitment_point, &revocation_key))
		abort();

	printf("Derived keys:\n");
	printf("  localkey: %s\n", fmt_pubkey(ctx, &localkey));
	printf("  remotekey: %s\n", fmt_pubkey(ctx, &remotekey));
	printf("  local_htlckey: %s\n", fmt_pubkey(ctx, &local_htlckey));
	printf("  remote_htlckey: %s\n", fmt_pubkey(ctx, &remote_htlckey));
	printf("  local_delayedkey: %s\n", fmt_pubkey(ctx, &local_delayedkey));
	printf("  revocation_key: %s\n", fmt_pubkey(ctx, &revocation_key));

	/* Expected keys from test vectors (decoded from signed HTLC success tx witness) */
	printf("\nExpected HTLC keys from test vectors:\n");
	printf("  remote_htlcpubkey: 03d8507a026fb30bcd48ee9c765c7346470d0d397661d43dd2eb601f661ab92a0b\n");
	printf("  local_htlcpubkey:  03c26117339025855b87deda5e138d438b2098881a5e6f81f72a60310faef473c6\n");

	/* Compute hash160 of revocation key and compare with expected */
	{
		u8 revkey_der[33];
		struct sha256 sha;
		struct ripemd160 hash160;
		pubkey_to_der(revkey_der, &revocation_key);
		sha256(&sha, revkey_der, sizeof(revkey_der));
		ripemd160(&hash160, sha.u.u8, sizeof(sha.u.u8));
		printf("  revocation_key hash160: ");
		for (int i = 0; i < 20; i++) printf("%02x", hash160.u.u8[i]);
		printf("\n");
		printf("  expected hash160:       ef8968bbfe34ad740642784d7b1efaebfd5b23ec\n\n");
	}

	/* Build keyset */
	struct keyset keyset;
	keyset.self_revocation_key = revocation_key;
	keyset.self_delayed_payment_key = local_delayedkey;
	keyset.self_payment_key = localkey;
	keyset.other_payment_key = remotekey;
	keyset.self_htlc_key = local_htlckey;
	keyset.other_htlc_key = remote_htlckey;

	/* Calculate commitment number obscurer */
	u64 cn_obscurer = commit_number_obscurer(&local_payment_basepoint, &remote_payment_basepoint);
	printf("Commitment number obscurer: 0x%"PRIx64"\n\n", cn_obscurer);

	/* Iterate through test cases */
	size_t test_idx;
	const jsmntok_t *test;
	int passed = 0, failed = 0;

	json_for_each_arr(test_idx, test, tests_tok) {
		const jsmntok_t *name_tok = json_get_member(json, test, "name");
		const jsmntok_t *dust_limit_tok = json_get_member(json, test, "dust_limit_satoshis");
		const jsmntok_t *to_local_tok = json_get_member(json, test, "to_local_msat");
		const jsmntok_t *to_remote_tok = json_get_member(json, test, "to_remote_msat");
		const jsmntok_t *signed_commit_tx_tok = json_get_member(json, test, "signed_commit_tx");

		if (!name_tok || !dust_limit_tok || !to_local_tok || !to_remote_tok || !signed_commit_tx_tok) {
			printf("Test %zu: SKIP (missing fields)\n", test_idx);
			continue;
		}

		char *name = json_strdup(ctx, json, name_tok);
		char *expected_tx_hex = json_strdup(ctx, json, signed_commit_tx_tok);

		u64 dust_limit_val, to_local_val, to_remote_val;
		if (!json_to_u64(json, dust_limit_tok, &dust_limit_val) ||
		    !json_to_u64(json, to_local_tok, &to_local_val) ||
		    !json_to_u64(json, to_remote_tok, &to_remote_val)) {
			printf("Test %zu: SKIP (invalid numeric values)\n", test_idx);
			continue;
		}

		struct amount_sat dust_limit = amount_sat(dust_limit_val);
		struct amount_msat to_local = amount_msat(to_local_val);
		struct amount_msat to_remote = amount_msat(to_remote_val);

		printf("Test %zu: %s\n", test_idx, name);
		printf("  dust_limit: %"PRIu64" sats\n", dust_limit.satoshis);
		printf("  to_local: %"PRIu64" msat\n", to_local.millisatoshis);
		printf("  to_remote: %"PRIu64" msat\n", to_remote.millisatoshis);

		/* Parse HTLCs if present */
		const jsmntok_t *incoming_htlcs_tok = json_get_member(json, test, "incoming_htlcs");
		const jsmntok_t *outgoing_htlcs_tok = json_get_member(json, test, "outgoing_htlcs");

		const struct htlc **htlcs = tal_arr(ctx, const struct htlc *, 0);

		/* Parse incoming HTLCs (RCVD from our perspective) */
		if (incoming_htlcs_tok && incoming_htlcs_tok->type == JSMN_ARRAY) {
			size_t htlc_idx;
			const jsmntok_t *htlc_tok;
			json_for_each_arr(htlc_idx, htlc_tok, incoming_htlcs_tok) {
				struct htlc *htlc = tal(htlcs, struct htlc);
				const jsmntok_t *id_tok = json_get_member(json, htlc_tok, "id");
				const jsmntok_t *amount_tok = json_get_member(json, htlc_tok, "amount_msat");
				const jsmntok_t *hash_tok = json_get_member(json, htlc_tok, "payment_hash");
				const jsmntok_t *expiry_tok = json_get_member(json, htlc_tok, "cltv_expiry");

				u64 id_val, amount_val, expiry_val;
				json_to_u64(json, id_tok, &id_val);
				json_to_u64(json, amount_tok, &amount_val);
				json_to_u64(json, expiry_tok, &expiry_val);

				htlc->id = id_val;
				htlc->amount = amount_msat(amount_val);
				htlc->expiry.locktime = expiry_val;
				htlc->state = RCVD_ADD_ACK_REVOCATION; /* Incoming */

				char *hash_hex = json_strdup(ctx, json, hash_tok);
				sha256_from_hex(hash_hex, &htlc->rhash);
				htlc->r = NULL; /* We don't need preimage for commitment tx */

				tal_arr_expand(&htlcs, htlc);
			}
		}

		/* Parse outgoing HTLCs (SENT from our perspective) */
		if (outgoing_htlcs_tok && outgoing_htlcs_tok->type == JSMN_ARRAY) {
			size_t htlc_idx;
			const jsmntok_t *htlc_tok;
			json_for_each_arr(htlc_idx, htlc_tok, outgoing_htlcs_tok) {
				struct htlc *htlc = tal(htlcs, struct htlc);
				const jsmntok_t *id_tok = json_get_member(json, htlc_tok, "id");
				const jsmntok_t *amount_tok = json_get_member(json, htlc_tok, "amount_msat");
				const jsmntok_t *hash_tok = json_get_member(json, htlc_tok, "payment_hash");
				const jsmntok_t *expiry_tok = json_get_member(json, htlc_tok, "cltv_expiry");

				u64 id_val, amount_val, expiry_val;
				json_to_u64(json, id_tok, &id_val);
				json_to_u64(json, amount_tok, &amount_val);
				json_to_u64(json, expiry_tok, &expiry_val);

				htlc->id = id_val;
				htlc->amount = amount_msat(amount_val);
				htlc->expiry.locktime = expiry_val;
				htlc->state = SENT_ADD_ACK_REVOCATION; /* Outgoing */

				char *hash_hex = json_strdup(ctx, json, hash_tok);
				sha256_from_hex(hash_hex, &htlc->rhash);
				htlc->r = NULL;

				tal_arr_expand(&htlcs, htlc);
			}
		}

		printf("  HTLCs: %zu total\n", tal_count(htlcs));

		/* Debug: print expected vs actual wscript for first HTLC */
		if (tal_count(htlcs) > 0 && incoming_htlcs_tok) {
			struct ripemd160 ripemd;
			ripemd160(&ripemd, htlcs[0]->rhash.u.u8, sizeof(htlcs[0]->rhash.u.u8));
			u8 *wscript = htlc_received_wscript(ctx, &ripemd, &htlcs[0]->expiry, &keyset,
							    false, true, true); /* option_zero_fee_commitments */
			printf("  First HTLC wscript: %s\n", tal_hex(ctx, wscript));
			printf("  Expected wscript:   76a914ef8968bbfe34ad740642784d7b1efaebfd5b23ec8763ac672103d8507a026fb30bcd48ee9c765c7346470d0d397661d43dd2eb601f661ab92a0b7c8201208763a914f4c8e88504a23ed3e390ea80300c834f0eb79a6c88527c2103c26117339025855b87deda5e138d438b2098881a5e6f81f72a60310faef473c652ae677503560a0eb175ac6868\n");
		}

		/* Build commitment transaction */
		const struct htlc **htlc_map;
		int anchor_outnum;
		struct bitcoin_tx *tx = commit_tx(
			ctx,
			&funding,
			funding_amount,
			&local_funding_pubkey,
			&remote_funding_pubkey,
			LOCAL, /* opener */
			to_self_delay,
			0, 0, /* No lease */
			&keyset,
			0, /* feerate_per_kw - ignored for zero-fee */
			dust_limit,
			to_local,
			to_remote,
			tal_count(htlcs) > 0 ? htlcs : NULL,
			&htlc_map,
			NULL, /* direct_outputs */
			commitment_number ^ cn_obscurer,
			false, /* option_anchor_outputs */
			true,  /* option_anchors_zero_fee_htlc_tx */
			true,  /* option_zero_fee_commitments */
			LOCAL,
			&anchor_outnum);

		/* Validate version 3 */
		printf("  TX version: %u (expected 3)\n", tx->wtx->version);
		if (tx->wtx->version != 3) {
			printf("  FAILED: Wrong version\n\n");
			failed++;
			continue;
		}

		/* Check for P2A anchor */
		bool found_p2a = false;
		struct amount_sat p2a_amount = AMOUNT_SAT(0);
		for (size_t i = 0; i < tx->wtx->num_outputs; i++) {
			const u8 *script = tx->wtx->outputs[i].script;
			size_t script_len = tx->wtx->outputs[i].script_len;
			if (is_p2a(script, script_len)) {
				found_p2a = true;
				bitcoin_tx_output_get_amount_sat(tx, i, &p2a_amount);
				break;
			}
		}
		printf("  P2A anchor: %s (amount: %"PRIu64" sats)\n",
		       found_p2a ? "found" : "MISSING", p2a_amount.satoshis);

		if (!found_p2a) {
			printf("  FAILED: Missing P2A anchor\n\n");
			failed++;
			continue;
		}

		/* Verify anchor cap (240 sats) */
		if (p2a_amount.satoshis > 240) {
			printf("  FAILED: P2A anchor exceeds 240 sat cap\n\n");
			failed++;
			continue;
		}

		/* Sign the transaction for full comparison */
		u8 *wscript = bitcoin_redeem_2of2(ctx, &local_funding_pubkey, &remote_funding_pubkey);
		struct bitcoin_signature localsig, remotesig;

		sign_tx_input(tx, 0, NULL, wscript,
			      &remote_funding_privkey, &remote_funding_pubkey,
			      SIGHASH_ALL, &remotesig);
		sign_tx_input(tx, 0, NULL, wscript,
			      &local_funding_privkey, &local_funding_pubkey,
			      SIGHASH_ALL, &localsig);

		u8 **witness = bitcoin_witness_2of2(tx, &localsig, &remotesig,
						    &local_funding_pubkey, &remote_funding_pubkey);
		bitcoin_tx_input_set_witness(tx, 0, take(witness));

		/* Compare with expected */
		u8 *serialized = linearize_tx(ctx, tx);
		char *our_hex = tal_hex(ctx, serialized);

		printf("  Num outputs: %zu\n", tx->wtx->num_outputs);
		printf("  Output hex length: %zu (expected %zu)\n",
		       strlen(our_hex), strlen(expected_tx_hex));

		if (strcasecmp(our_hex, expected_tx_hex) == 0) {
			printf("  PASSED: Exact match!\n\n");
			passed++;
		} else {
			printf("  MISMATCH - dumping details:\n");
			printf("  Expected: %s\n", expected_tx_hex);
			printf("  Got:      %s\n", our_hex);

			/* Decode outputs for comparison */
			for (size_t i = 0; i < tx->wtx->num_outputs; i++) {
				struct amount_sat out_amt;
				bitcoin_tx_output_get_amount_sat(tx, i, &out_amt);
				const u8 *script = tx->wtx->outputs[i].script;
				size_t script_len = tx->wtx->outputs[i].script_len;
				printf("  Output %zu: %"PRIu64" sats, script=%s\n",
				       i, out_amt.satoshis, tal_hex(ctx, tal_dup_arr(ctx, u8, script, script_len, 0)));
			}
			printf("\n");
			failed++;
		}

		tal_free(htlcs);
	}

	printf("# ============================================================\n");
	printf("# Summary: %d passed, %d failed\n", passed, failed);
	printf("# ============================================================\n");

	if (failed > 0) {
		printf("FAIL\n");
		return 1;
	}

cleanup:
	tal_free(ctx);
	common_shutdown();
	return 0;
}
